### ISSUE TITLE
relatedness results question

### ISSUE THREAD

**Issue by JonEilers** [brentp/somalier#78]
Hi, 
I am trying to help a family resolve some relatedness questions. I have vcf files for a daughter, mother, and grandmother. It is thought that the grandmother is not related to the daughter/mother and ancestry analysis supports this (phillipines/chinese vs mongolia/sibera/kazakhstan. However, when running the vcfs through somalier, the grandmother to mother relationship is .44. The mother to daughter is .504 and the daughter to grandmother is .07

So I am kinda scratching my head. Any suggestions on what I could do next to resolve this or how I should interpret this?

**Comment by brentp** [comment]
hmm. this is interesting. can you share the html output from somalier? you can send to my email if you can and prefer.

otherwise, do you have these samples as part of a larger cohort? 
sometimes, if a samples has low quality, the relatedness estimates can be off but it helps to have a few unrelated samples in the cohort to be able to gauge.

**Comment by JonEilers** [comment]
I can email you the html files. What's your email? 
I added my vcf into the cohort but I'm the only unrelated person in the cohort.

**Comment by brentp** [comment]
bpederse@gmail.com

so were these VCFs jointly called? If not, can you run somalier on the bam or cram files? that will give a more accurate estimate.

**Comment by JonEilers** [comment]
@brentp email sent. 
My background is in genome assembly/annotation so I am not very familiar with variant calling, but I included in the email the commands I used to index/extract/run somalier on the vcf files.
